; Generated by frame2arm (C++ generator)
; Mask: /Users/ricer/scripts/bad-apple/mask.txt  mask size=10x10  pixels=36
    MOV R0, #0x000000    ; black
    MOV R1, #.PixelScreen
    MOV R2, #base_offsets    ; address of base offsets list
    MOV R3, #36    ; number of black pixels in mask
    MOV R4, #shifts
    MOV R5, #96    ; frames count
    MOV R6, #0    ; current frame index
frame_loop:
    MOV R7, R6
    LSL R7, R7, #2      ; R7 = R6 * 4 (byte offset into shifts)
    ADD R7, R7, R4      ; R7 = &shifts + index*4
    LDR R8, [R7]        ; R8 = shift in bytes for this frame
    MOV R9, R2          ; pointer to base_offsets array
    MOV R10, #0         ; pixel loop idx
pixel_loop:
    LDR R11, [R9]       ; base offset for pixel
    ADD R11, R11, R8    ; add frame shift
    STR R0, [R1+R11]    ; draw black pixel
    ADD R9, R9, #4      ; next base_offsets
    ADD R10, R10, #1
    CMP R10, R3
    BLT pixel_loop
    ADD R6, R6, #1
    CMP R6, R5
    BLT frame_loop
    HALT

.DATA
base_offsets:
    .WORD 264
    .WORD 268
    .WORD 272
    .WORD 276
    .WORD 280
    .WORD 284
    .WORD 516
    .WORD 520
    .WORD 524
    .WORD 528
    .WORD 532
    .WORD 536
    .WORD 540
    .WORD 544
    .WORD 772
    .WORD 776
    .WORD 780
    .WORD 784
    .WORD 788
    .WORD 792
    .WORD 796
    .WORD 800
    .WORD 1028
    .WORD 1032
    .WORD 1036
    .WORD 1040
    .WORD 1044
    .WORD 1048
    .WORD 1052
    .WORD 1056
    .WORD 1288
    .WORD 1292
    .WORD 1296
    .WORD 1300
    .WORD 1304
    .WORD 1308

shifts:
    .WORD 0
    .WORD 4
    .WORD 8
    .WORD 12
    .WORD 16
    .WORD 20
    .WORD 24
    .WORD 28
    .WORD 32
    .WORD 36
    .WORD 40
    .WORD 44
    .WORD 48
    .WORD 52
    .WORD 56
    .WORD 60
    .WORD 64
    .WORD 68
    .WORD 72
    .WORD 76
    .WORD 80
    .WORD 84
    .WORD 88
    .WORD 92
    .WORD 96
    .WORD 100
    .WORD 104
    .WORD 108
    .WORD 112
    .WORD 116
    .WORD 120
    .WORD 124
    .WORD 128
    .WORD 132
    .WORD 136
    .WORD 140
    .WORD 144
    .WORD 148
    .WORD 152
    .WORD 156
    .WORD 160
    .WORD 164
    .WORD 168
    .WORD 172
    .WORD 176
    .WORD 180
    .WORD 184
    .WORD 188
    .WORD 192
    .WORD 196
    .WORD 200
    .WORD 204
    .WORD 208
    .WORD 212
    .WORD 216
    .WORD 0
    .WORD 4
    .WORD 8
    .WORD 12
    .WORD 16
    .WORD 20
    .WORD 24
    .WORD 28
    .WORD 32
    .WORD 36
    .WORD 40
    .WORD 44
    .WORD 48
    .WORD 52
    .WORD 56
    .WORD 60
    .WORD 64
    .WORD 68
    .WORD 72
    .WORD 76
    .WORD 80
    .WORD 84
    .WORD 88
    .WORD 92
    .WORD 96
    .WORD 100
    .WORD 104
    .WORD 108
    .WORD 112
    .WORD 116
    .WORD 120
    .WORD 124
    .WORD 128
    .WORD 132
    .WORD 136
    .WORD 140
    .WORD 144
    .WORD 148
    .WORD 152
    .WORD 156
    .WORD 160
